{"name": "test_login_0_user_wrongFormat[data5]", "status": "passed", "description": "\n        异常用例 - 登录失败-数据不正确\n        步骤:\n         1.输入用户名：XX 密码：XX 点击登录\n         2. 断言： 登录页面 提示 - XXX\n              登录页面中 - 获取提示框的文本内容\n              比对文本内容 与 期望的值 是否相等。\n        :param data:\n        :param access_web1:\n        :return:\n        ", "attachments": [{"name": "log", "source": "3d70db55-5eb8-4e1d-9c50-842b777edf23-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': 55173206, 'passwd': 55173206, 'check': '账号或密码错误，还有[2]次将锁定账号', 'explain': '账号密码错误'}"}], "start": 1596259447914, "stop": 1596259448735, "uuid": "e20ab91e-68f7-4c8a-a98e-7840ab877f25", "historyId": "5006556a359f56c3b01f8dc0028ef47b", "testCaseId": "fe0639cb41592b40517b5dd1e2687260", "fullName": "test_login_xcfb.TestLoginXcfb#test_login_0_user_wrongFormat", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page1')"}, {"name": "suite", "value": "test_login_xcfb"}, {"name": "subSuite", "value": "TestLoginXcfb"}, {"name": "host", "value": "DESKTOP-6E8RQN3"}, {"name": "thread", "value": "33204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_xcfb"}]}