{"name": "test_login_0_user_wrongFormat[data4]", "status": "passed", "description": "\n        异常用例 - 登录失败-数据不正确\n        步骤:\n         1.输入用户名：XX 密码：XX 点击登录\n         2. 断言： 登录页面 提示 - XXX\n              登录页面中 - 获取提示框的文本内容\n              比对文本内容 与 期望的值 是否相等。\n        :param data:\n        :param access_web1:\n        :return:\n        ", "attachments": [{"name": "log", "source": "7d58980a-21cb-4ecf-94e8-2e43c7258490-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': 55173206, 'passwd': 55173206, 'check': '账号或密码错误，还有[3]次将锁定账号', 'explain': '账号密码错误'}"}], "start": 1596259446439, "stop": 1596259447251, "uuid": "7b30c2ab-0fbc-4b5e-ae87-d71d006eece8", "historyId": "8a5a6faa25599199ac3c9861539bce36", "testCaseId": "fe0639cb41592b40517b5dd1e2687260", "fullName": "test_login_xcfb.TestLoginXcfb#test_login_0_user_wrongFormat", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page1')"}, {"name": "suite", "value": "test_login_xcfb"}, {"name": "subSuite", "value": "TestLoginXcfb"}, {"name": "host", "value": "DESKTOP-6E8RQN3"}, {"name": "thread", "value": "33204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_xcfb"}]}